name: 'Setup Node.js from .nvmrc'
description: 'Sets up Node.js using the version specified in .nvmrc file'
runs:
  using: "composite"
  steps:
    - name: Get Node.js version
      id: nvm
      shell: bash
      run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
